### ISSUE TITLE
Update docs with tracing config to export variables

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-mi#1211]
### Description

We can export variables in tracing data using the following TOML config. We need to update the docs accordingly.

```toml
[mediation]
stat.tracer.collect_mediation_variables= true
```

**Related PR:**

https://github.com/wso2/wso2-synapse/pull/2269
