### ISSUE TITLE
Update toml config in Synapse Handlers

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-mi#258]
**Description:**
The toml config given in the doc[1] is incorrect. It should be as follows,

```toml
[[synapse_handlers]]
name = "<handlerName>"
class = "<packageName>.<handlerName>"
```

[1] - https://mi.docs.wso2.com/en/latest/develop/customizations/creating-synapse-handlers/
